- id: '1652986565590'
  alias: Test UI automation
  description: Create an automation through the UI
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: python_script.pass
    data: {}
  mode: single
- id: '1652987217732'
  alias: Another test script created through the UI
  description: Another test script created through the UI - Description
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: python_script.pass
    data: {}
  mode: single
