- id: '1666459332521'
  alias: ZEN32 (Z-Wave JS)
  description: Back Patio Scene Controller
  use_blueprint:
    path: fxlt/zen32-scene-controller-z-wave-js.yaml
    input:
      zooz_switch: 07246240d9419e3d49565c2c0a75d8ef
      scene_1:
      - service: switch.toggle
        data: {}
        target:
          entity_id:
          - switch.string_lights
      scene_2:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.pentair_fb_bb_80_pool_light
      scene_3:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.pentair_fb_bb_80_water_feature
      scene_4:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.kitchen_lights
      scene_32: []
      scene_42: []
      scene_43: []
      scene_44: []
      scene_12: []
      scene_22: []
- id: '1704472961581'
  alias: 'Lights: Turn kitchen light on when breakfast area is turned on'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.breakfast_area_light
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.kitchen_lights
    data: {}
  mode: single
- id: '1704473187617'
  alias: 'Lights: Turn kitchen lights off when breakfast area light turns off'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.breakfast_area_light
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.kitchen_lights
    data: {}
  mode: single
- id: '1714247307062'
  alias: 'Switch: Turn on family room ceiling fan when switch turns on'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.ceiling_fan_wall
    from: 'off'
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.family_room_ceiling_fan
  mode: single
- id: '1714247668584'
  alias: 'Switch: Turn off family room ceiling fan when switch turns off'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.ceiling_fan_wall
    from: 'on'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.family_room_ceiling_fan
    data: {}
  mode: single
- id: '1714248744883'
  alias: 'Switch: Turn off family room ceiling light when switch turns off'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.dimmer_dry_contact_relay
    from: 'on'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.family_room_ceiling_light
  mode: single
- id: '1714248955585'
  alias: 'Switch: Turn on family room ceiling light when switch turns on'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.dimmer_dry_contact_relay
    from: 'off'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.family_room_ceiling_light
  mode: single
- id: '1717255351839'
  alias: 'Media: TV Audio Power On'
  description: Turn on audio when TV turns on
  triggers:
  - device_id: ba9913ecc8e7a11050ca5d064df0160a
    domain: media_player
    entity_id: 1b6f6bd2e67a76d8e4ec51c0279dadce
    type: turned_on
    trigger: device
  conditions: []
  actions:
  - action: media_player.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: media_player.family_room_tv_audio
  mode: single
- id: '1717255483592'
  alias: 'Media: TV Audio power Off'
  description: Turn off audio when TV turns off
  triggers:
  - device_id: ba9913ecc8e7a11050ca5d064df0160a
    domain: media_player
    entity_id: 1b6f6bd2e67a76d8e4ec51c0279dadce
    type: turned_off
    trigger: device
  conditions: []
  actions:
  - action: media_player.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: media_player.family_room_tv_audio
  mode: single
- id: '1717880805166'
  alias: DS Bathroom Light On
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.ds_bathroom_paddle
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      device_id: 984c38439b259b91d4e2e830df6ec337
  mode: single
- id: '1717880924305'
  alias: 'Lights: DS Bathroom Off'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.ds_bathroom_paddle
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    target:
      device_id: 984c38439b259b91d4e2e830df6ec337
    data: {}
  mode: single
- id: '1725747666470'
  alias: 'Media: Turn on Patio Speakers when Patio TV turns on'
  description: Turn on audio when TV turns on
  trigger:
  - platform: device
    device_id: fec97e513df33ac2fb7a8799b5fa51d0
    domain: media_player
    entity_id: c39f118ecb466d2a324526ed24229a29
    type: playing
  condition: []
  action:
  - service: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.patio_tv_audio_on
  mode: single
- id: '1734192737016'
  alias: 'Keyfob: TV Volume Up'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.keyfob_scene_006
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: event.keyfob_scene_006
        attribute: event_type
        state: KeyPressed
      sequence:
      - action: input_boolean.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.family_room_tv_volume_up
  mode: single
- id: '1734192859778'
  alias: 'Keyfob: TV Volume Down'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.keyfob_scene_005
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: event.keyfob_scene_005
        attribute: event_type
        state: KeyPressed
      sequence:
      - action: input_boolean.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.family_room_tv_volume_down
  mode: single
