- id: '1666459332521'
  alias: ZEN32 (Z-Wave JS)
  description: Back Patio Scene Controller
  use_blueprint:
    path: fxlt/zen32-scene-controller-z-wave-js.yaml
    input:
      zooz_switch: 07246240d9419e3d49565c2c0a75d8ef
      scene_1:
      - service: switch.toggle
        data: {}
        target:
          entity_id:
          - switch.string_lights
      scene_2:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.pentair_fb_bb_80_pool_light
      scene_3:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.pentair_fb_bb_80_water_feature
      scene_4:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.kitchen_lights
      scene_32: []
      scene_42: []
      scene_43: []
      scene_44: []
      scene_12: []
      scene_22: []
- id: '1704472961581'
  alias: 'Lights: Turn kitchen light on when breakfast area is turned on'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.breakfast_area_light
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.kitchen_lights
    data: {}
  mode: single
- id: '1704473187617'
  alias: 'Lights: Turn kitchen lights off when breakfast area light turns off'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.breakfast_area_light
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.kitchen_lights
    data: {}
  mode: single
- id: '1714247307062'
  alias: 'Switch: Turn on family room ceiling fan when switch turns on'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.ceiling_fan_wall
    from: 'off'
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.family_room_ceiling_fan
  mode: single
- id: '1714247668584'
  alias: 'Switch: Turn off family room ceiling fan when switch turns off'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.ceiling_fan_wall
    from: 'on'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.family_room_ceiling_fan
    data: {}
  mode: single
- id: '1714248744883'
  alias: 'Switch: Turn off family room ceiling light when switch turns off'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.dimmer_dry_contact_relay
    from: 'on'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.family_room_ceiling_light
  mode: single
- id: '1714248955585'
  alias: 'Switch: Turn on family room ceiling light when switch turns on'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.dimmer_dry_contact_relay
    from: 'off'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.family_room_ceiling_light
  mode: single
