homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation

    # metric for Metric, imperial for Imperial
  unit_system: imperial

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Phoenix
  country: US
  currency: USD

  # Customization file
  customize: !include customize.yaml

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/16      

  external_url: https://eric70x7.duckdns.org

# Enable the default set of integrations:
default_config:
  
# Use lovelace YAML mode
lovelace:
  mode: yaml
  
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Log levels
logger:
  default: critical
  logs:
    homeassistant.components.python_script: info
    pybalboa: debug
    homeassistant.components.balboa: debug
    
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Python
python_script:

# ifttt
ifttt:
  key: !secret ifttt_key

# Alexa
alexa:

# Sense energy monitor
# sense:
#  email: !secret sense_email
#  password: !secret sense_password

# Ambient weather
ambient_station:
  api_key: !secret ambient_api_key
  app_key: !secret ambient_app_key

# Z-wave
# commented out after upgrading to zwave JS
# zwave:
#   usb_path: /dev/ttyACM0
#   device_config: !include zwave.yaml
    
# Turn on system health monitor
system_health:

# Timers
timer:
  dog_lights:
    duration: "00:05:00"
  wind_watchdog:
    duration: "00:15:00"

# media
# media_player:
#  - platform: samsungtv
#    name: family_room_tv
#  - platform: samsungtv
#    name: living_room_un65ju639d
#  - platform: androidtv
#    name: family_room_firestick
#    host: 192.168.0.3
#  - platform: androidtv
#    name: loft_firestick
#    host: 192.168.0.13

# ios actions for Apple Watch
ios:
  actions:
    - name: "Desk lights"
      icon:
        icon: lightbulb
      label:
        text: "Desk lights"
    - name: "Master light"
      icon:
        icon: lightbulb
      label:
        text: "Master light"

recorder: !include recorder.yaml
input_number: !include input_numbers.yaml
# input_booleans: !include input_booleans.yaml
http: !include http.yaml
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
# switch: !include switches.yaml
group: !include groups.yaml
automation ui: !include automations.yaml
automation mine: !include my_automations.yaml
script: !include_dir_merge_named scripts/
cover: !include covers.yaml

influxdb:
  api_version: 1
  host: 192.168.0.3 # js1
  include:
    domains:
      - sensor
      - input_number
#    entities:
#      - sensor.energy_usage
#      - sensor.1_hr_demand
#      - sensor.fast_demand
#      - sensor.medium_demand
#      - sensor.medium_long_demand
#      - sensor.ambient_temp
#      - sensor.ambient_uv
#      - sensor.ambient_temp_1 # Upstairs
#      - sensor.ambient_temp_2 # Downstairs
#      - sensor.ambient_temp_6 # Becca
#      - sensor.ambient_temp_7 # Neil

# Themes
# enable mobile component
# mobile_app:
  
# Enables a map showing the location of tracked devices
# map:

# Track the sun
# sun:

frontend:
  themes:
    # From https://community.home-assistant.io/t/dark-cyan-theme/28594?u=frenck
    BlueNight:
      # MyVariables
      base-hue: '220' #Controls the base (and accent) color hue (0-360) | 0=Red 60=Yellow 120=Green 180=Cyan 240=Blue 300=Magenta 360=Red
      base-sat: '5%' #Controls the saturation of the theme (0%-100%) | 0%=Grey 100%=Full Saturation
      # MyVar
      huesat: 'var(--base-hue), var(--base-sat),'
      # Primary Color
      primary-color: '#2581ab' #hsl(var(--huesat) 50%)' #header colors and some text colors
      dark-primary-color: 'hsl(var(--huesat) 60%)'
      light-primary-color: 'hsl(var(--huesat) 30%)'
      accent-color: 'hsl(var(--huesat) 30%)'
      medium-grey-color: '#202020'
      # Backgrounds
      primary-background-color: 'hsl(var(--huesat) 16%)'
      secondary-background-color: 'hsl(var(--huesat) 16%)' # background behind cards
      paper-listbox-background-color: 'hsl(var(--huesat) 16%)'
      paper-card-background-color: 'hsl(var(--huesat) 12%)'
      paper-dialog-background-color: 'var(--paper-card-background-color)'
      table-row-background-color: 'hsl(var(--huesat) 12%)'
      table-row-alternative-background-color: 'hsl(var(--huesat) 10%)'
      card-background-color: 'var(--paper-card-background-color)'
      # Divider
      divider-color: 'hsla(0, 0%, 0%, 0)'
      dark-divider-opacity: '0'
      light-divider-opacity: '0'
      dark-secondary-opacity: '1'
      # Text colors
      primary-text-color: 'hsl(var(--huesat) 90%)'
      text-primary-color: 'hsl(var(--huesat) 90%)'
      secondary-text-color: 'hsl(var(--huesat) 80%)'
      disabled-text-color: 'hsl(var(--huesat) 70%)'
      sidebar-text_-_color: 'hsl(var(--huesat) 90%)'
      sidebar-text-color: 'hsl(var(--huesat) 90%)'
      paper-card-header-color: 'hsl(var(--huesat) 90%)'
      paper-button-ink-color: 'hsl(var(--huesat) 50%)'
      # Text Adjustments
      paper-font-headline_-_letter-spacing: '-0.5px'
      paper-font-headline_-_font-weight: '400'
      paper-font-body1_-_font-weight: '300'
      # Nav Menu
      paper-listbox-color: 'hsl(var(--huesat) 50%)'
      paper-grey-50: 'hsl(var(--huesat) 50%)'
      paper-grey-200: 'hsl(var(--huesat) 10%)' #active menu item
      sidebar-icon-color: 'hsl(var(--huesat) 50%)' #iron-icon-fill-color
      # Paper card
      paper-item-icon-color: 'hsl(var(--huesat) 40%)'
      #paper-item-icon-active-color: 'var(--paper-item-icon-color)'
      paper-item-icon_-_color: 'var(--paper-item-icon-color)'
      paper-item-selected_-_background-color: 'hsla(0, 0%, 0%, 0.2)'
      paper-item-selected_-_color: 'hsl(var(--huesat) 20%)' #?
      paper-tabs-selection-bar-color: 'hsla(0, 0%, 0%, 0.2)'
      paper-tab-ink: 'hsl(var(--huesat) 70%)'
      paper-input-container-color: 'hsl(var(--huesat) 60%)'
      # Labels
      label-badge-red: 'hsl(20, 50%, 25%)'
      label-badge-border-color: 'var(--label-badge-red)'
      label-badge-background-color: 'var(--paper-card-background-color)'
      label-badge-text-color: 'var(--primary-text-color)'
      # Shadows
      shadow-elevation-2dp_-_box-shadow: '0px 0px 0px 0px hsl(var(--huesat) 10%)'
      shadow-elevation-16dp_-_box-shadow: '0px 0px 0px 0px hsl(var(--huesat) 25%)'
      # Switches
      paper-toggle-button-checked-button-color: 'hsl(var(--base-hue), 90%, 50%)'
      paper-toggle-button-checked-bar-color: 'hsl(var(--huesat) 25%)'
      paper-toggle-button-unchecked-button-color: 'hsl(var(--huesat) 25%)'
      paper-toggle-button-unchecked-bar-color: 'hsl(var(--huesat) 5%)'
      # Sliders
      paper-slider-knob-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-knob-start-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-slider-pin-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-active-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-container-color: 'hsl(var(--huesat) 28%)'
      paper-slider-secondary-color: 'hsl(var(--huesat) 90%)'
      paper-slider-disabled-active-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-slider-disabled-secondary-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-dialog-color: 'hsl(var(--base-hue), 20%, 80%)'
      
      #Changes to fix history/logbook menus
      lumo-primary-text-color: 'var(--primary-color)'
      lumo-secondary-text-color: 'var(--primary-color)'
      lumo-primary-color: 'var(--primary-color)'
      lumo-primary-color-50pct: 'rgba(37,129,172, .5)'
      lumo-primary-color-10pct: 'rgba(37,129,172, .1)'
      #Calendar day numbers
      lumo-body-text-color: 'var(--primary-text-color)'
      #Calendar/Date-Picker Background
      lumo-base-color: 'var(--medium-grey-color)'
      #Month/Year header
      lumo-header-text-color: 'var(--lumo-body-text-color)'
      #DayOfWeek Header
      lumo-tertiary-text-color: 'var(--lumo-body-text-color)'
      # Background of date in History/Logbook that you clcim to view date-picker
      lumo-shade: 'var(--medium-grey-color)'
      lumo-shade-90pct: 'rgba(41, 41, 41, .9)'
      lumo-shade-80pct: 'rgba(41, 41, 41, .8)'
      lumo-shade-70pct: 'rgba(41, 41, 41, .7)'
      lumo-shade-60pct: 'rgba(41, 41, 41, .6)'
      lumo-shade-50pct: 'rgba(41, 41, 41, .5)'
      lumo-shade-40pct: 'rgba(41, 41, 41, .4)'
      lumo-shade-30pct: 'rgba(41, 41, 41, .3)'
      lumo-shade-20pct: 'rgba(41, 41, 41, .2)'
      lumo-shade-10pct: 'rgba(41, 41, 41, .1)'
      lumo-shade-5pct: 'rgba(41, 41, 41, .05)'
      #Removes Gradient in Calendar/Date-Picker and Drop-down lists
      lumo-tint-5pct: 'var(--darker-grey-color)'
