homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation

  # metric for Metric, imperial for Imperial
  unit_system: imperial

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Phoenix

  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - directv

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Log levels
logger:
  default: critical
  logs:
    homeassistant.components.python_script: info

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Python
python_script:

# Cloud
cloud:

# ifttt
ifttt:
  key: !secret ifttt_key

# Alexa
alexa:

# Sense energy monitor
sense:
  email: !secret sense_email
  password: !secret sense_password

# DNS service
duckdns:
  domain: eric70x7
  access_token: !secret duckdns_token

# Wink
wink:

system_health:

#media_player:
#  - platform: directv
#    host: 192.168.0.61
#    port: 8080
#    name: DirecTV DVR
#    device: 0
    
history_graph:
  gr1:
    name: Upstairs
    entities:
      - sensor.upstairs_temperature
      - sensor.upstairs_setpoint
      - sensor.upstairs_cooling
    hours_to_show: 6
  gr2:
    name: Downstairs
    entities:
      - sensor.downstairs_temperature
      - sensor.downstairs_setpoint
      - sensor.downstairs_cooling
    hours_to_show: 6
  gr3:
    name: Demand
    entities:
      - sensor.5_min_demand
      - sensor.15_min_demand
      - sensor.1_hr_demand
      - sensor.backyard_temperature
    hours_to_show: 6

input_number:
  kwh_limit:
    name: Demand Limit
    initial: 2.0
    min: 0.5
    max: 5.0
    step: 0.1
  hi_temp:
    name: High Temperature Limit
    initial: 80
    min: 65
    max: 85
    step: 1
  target_temp:
    name: Target Temperature
    initial: 70
    min: 65
    max: 85
    step: 1

http: !include http.yaml
sensor: !include_dir_merge_list sensors/
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

