homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation

  # metric for Metric, imperial for Imperial
  unit_system: us_customary

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Phoenix
  country: US
  currency: USD

  # Customization file
  customize: !include customize.yaml

  auth_providers:
    - type: homeassistant
      trusted_networks:
        - 192.168.0.0/16      

  external_url: https://eric70x7.duckdns.org

# For doorbell live streaming
ffmpeg:

#amcrest:
#  - host: 192.168.0.22
#    username: default
#    password: !secret doorbell_password#

# Enable the default set of integrations:
default_config:
  
# Activate the configuration editor
config:

# Use lovelace YAML mode
lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Jones
      icon: mdi:script
      show_in_sidebar: true
      filename: lovelace.yaml
frontend:
  extra_module_url: 
    - /local/card-mod.js
  
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Log levels
logger:
  default: info
  # logs:
    # homeassistant.components.python_script: info
    # pybalboa: debug
    # homeassistant.components.balboa: debug
    # custom_components.pyscript: debug
    
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Python
python_script:

# ifttt
ifttt:
  key: !secret ifttt_key

# Alexa
alexa:

# Sense energy monitor
# sense:
#  email: !secret sense_email
#  password: !secret sense_password

# Ambient weather
ambient_station:
  api_key: !secret ambient_api_key
  app_key: !secret ambient_app_key

# Z-wave
# commented out after upgrading to zwave JS
# zwave:
#   usb_path: /dev/ttyACM0
#   device_config: !include zwave.yaml
    
# Turn on system health monitor
system_health:

# Timers
timer:
  dog_lights:
    duration: "00:10:00"
  wind_watchdog:
    duration: "00:15:00"
  energy_watchdog:
    duration: "00:05:00"

# Whole house audio
media_player:
  - platform: xantech
    type: dax88
    port: socket://192.168.0.88:8888
    # port: socket://192.168.0.61:8888 # Port forwarded through ASUS router
    zones:
      11:
        name: "Patio"
      14:
        name: "Front"
      15:
        name: "Rear"
      16:
        name: "Center"
    sources:
      1:
        name: "Front"
      2:
        name: "Rear"
      3:
        name: "Center"
      5:
        name: "Family Room TV"
      6:
        name: "Sonos"
      7:
        name: "Patio TV"
  - platform: group
    name: Family Room TV Audio
    entities:
      - media_player.xantech8_center
      - media_player.xantech8_front
      - media_player.xantech8_rear


# ios actions for Apple Watch
ios:
  actions:
    - name: "Desk lights"
      icon:
        icon: lightbulb
      label:
        text: "Desk lights"
    - name: "Master light"
      icon:
        icon: lightbulb
      label:
        text: "Master light"

recorder: !include recorder.yaml
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml
http: !include http.yaml
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
# switch: !include switches.yaml
group: !include groups.yaml
automation ui: !include automations.yaml
automation mine: !include my_automations.yaml
script ui: !include scripts.yaml
script mine: !include_dir_merge_named scripts/
cover: !include covers.yaml
scene: !include scenes.yaml

light:
  - platform: template
    lights:
      family_room_log_light:
        turn_on:
        turn_off:
        set_level:
  - platform: template
    lights:
      breakfast_area_log_light:
        turn_on:
        turn_off:
        set_level:
  - platform: template
    lights:
      kitchen_log_light:
        turn_on:
        turn_off:
        set_level:

#template:
#  - number:
#    - name: Family room TV volume
#      state: "{{ (states('input_number.family_room_tv_volume') | float) | round(2) }}"

influxdb:
  api_version: 1
  host: 192.168.0.51 # js3
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  tags_attributes:
    - friendly_name
  include:
    domains:
      - sensor
      - input_number
      - media_player
      - select

utility_meter:
  daily_energy:
    source: sensor.energy_usage
    name: Daily Energy Meter
    # cycle: daily
    # Hack: cycle 1 min before midnight to 
    # keep the timestamp on the current day
    cron: "59 23 * * *"
    tariffs:
      - peak
      - offpeak
  monthly_energy:
    source: sensor.energy_usage
    name: Monthly Energy Meter
    cycle: monthly
    offset:
      days: 5
    tariffs:
      - peak
      - offpeak
