homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation

  # metric for Metric, imperial for Imperial
  unit_system: imperial

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Phoenix

  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# ifttt
ifttt:
  key: !secret ifttt_key

# Alexa
alexa:

# Sense energy monitor
sense:
  email: !secret sense_email
  password: !secret sense_password

# DNS service
duckdns:
  domain: eric70x7
  access_token: !secret duckdns_token

# Wink
wink:

http: !include http.yaml
sensor: !include_dir_merge_list sensors/
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
