homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation

  # metric for Metric, imperial for Imperial
  unit_system: us_customary

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Phoenix
  country: US
  currency: USD

  # Customization file
  customize: !include customize.yaml

  auth_providers:
    - type: homeassistant
      trusted_networks:
        - 192.168.0.0/16      

  external_url: https://eric70x7.duckdns.org

# For doorbell live streaming
ffmpeg:

# Enable the default set of integrations:
default_config:
  
# Activate the configuration editor
config:

# Use lovelace YAML mode
lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Jones
      icon: mdi:script
      show_in_sidebar: true
      filename: lovelace.yaml
frontend:
  extra_module_url: 
    - /local/card-mod.js
  
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Log levels
logger:
  default: info
  # logs:
    # homeassistant.components.python_script: info
    # pybalboa: debug
    # homeassistant.components.balboa: debug
    # custom_components.pyscript: debug
    
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Python
python_script:

# ifttt
ifttt:
  key: !secret ifttt_key

# Alexa
alexa:

# Ambient weather
# ambient_station:
#   api_key: !secret ambient_api_key
#   app_key: !secret ambient_app_key

# Turn on system health monitor
system_health:

# Timers
timer:
  dog_lights:
    duration: "00:10:00"
  wind_watchdog:
    duration: "00:15:00"
  energy_watchdog:
    duration: "00:10:00"

# Whole house audio
media_player:
  - platform: xantech
    type: dax88
    port: socket://192.168.0.122:8888 # js2 via lan
    zones:
      11:
        name: "Patio"
      14:
        name: "Front"
      15:
        name: "Rear"
      16:
        name: "Center"
    sources:
      1:
        name: "Front"
      2:
        name: "Rear"
      3:
        name: "Center"
      5:
        name: "Family Room TV"
      6:
        name: "Sonos"
      7:
        name: "Patio TV"
  - platform: group
    name: Family Room TV Audio
    entities:
      - media_player.xantech8_center
      - media_player.xantech8_front
      - media_player.xantech8_rear


# ios actions for Apple Watch
ios:
  actions:
    - name: "Desk lights"
      icon:
        icon: lightbulb
      label:
        text: "Desk lights"
    - name: "Master light"
      icon:
        icon: lightbulb
      label:
        text: "Master light"

recorder: !include recorder.yaml
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml
http: !include http.yaml
sensor: !include_dir_merge_list sensors/
# binary_sensor: !include_dir_merge_list binary_sensors/
# switch: !include switches.yaml
group: !include groups.yaml
automation ui: !include automations.yaml
automation mine: !include my_automations.yaml
script ui: !include scripts.yaml
script mine: !include_dir_merge_named scripts/
cover: !include covers.yaml
scene: !include scenes.yaml

template:
- sensor:
  # Upstairs climate
  - name: Upstairs Trane Temperature
    unit_of_measurement: '°F'
    state: >
      {{ state_attr('climate.upstairs_trane_thermostat', 'current_temperature') }}
  - name: Upstairs Cool Setpoint
    unit_of_measurement: '°F'
    state: >
      {% if state_attr('climate.upstairs_trane_thermostat.target_temp_high', 'target_temp_high') == None %}
        {{ state_attr('climate.upstairs_trane_thermostat', 'temperature') }}
      {% else %}
        {{ state_attr('climate.upstairs_trane_thermostat', 'target_temp_high') }}
      {% endif %}
  - name: Upstairs Heat Setpoint
    unit_of_measurement: '°F'
    state: >
      {% if state_attr('climate.upstairs_trane_thermostat.target_temp_high', 'target_temp_low') == None %}
        {{ state_attr('climate.upstairs_trane_thermostat', 'temperature') }}
      {% else %}
        {{ state_attr('climate.upstairs_trane_thermostat', 'target_temp_low') }}
      {% endif %}
  - name: Upstairs State
    state: >
      {{ state_attr('climate.upstairs_trane_thermostat', 'hvac_action') }}
  - name: Upstairs cooling
    state: >
      {% if is_state_attr('climate.upstairs_trane_thermostat', 'hvac_action', 'cooling') %}
        {{ 1 | int }}
      {% else %}
        {{ 0 | int }}
      {% endif %}
  # Downstairs climate
  - name: Downstairs Trane Temperature
    unit_of_measurement: '°F'
    state: >
      {{ state_attr('climate.downstairs_trane_thermostat', 'current_temperature') }}
  - name: Downstairs Cool Setpoint
    unit_of_measurement: '°F'
    state: >
      {% if state_attr('climate.downstairs_trane_thermostat.target_temp_high', 'target_temp_high') == None %}
        {{ state_attr('climate.downstairs_trane_thermostat', 'temperature') }}
      {% else %}
        {{ state_attr('climate.downstairs_trane_thermostat', 'target_temp_high') }}
      {% endif %}
  - name: Downstairs Heat Setpoint
    unit_of_measurement: '°F'
    state: >
      {% if state_attr('climate.downstairs_trane_thermostat.target_temp_high', 'target_temp_low') == None %}
        {{ state_attr('climate.downstairs_trane_thermostat', 'temperature') }}
      {% else %}
        {{ state_attr('climate.downstairs_trane_thermostat', 'target_temp_low') }}
      {% endif %}
  - name: Downstairs State
    state: >
      {{ state_attr('climate.downstairs_trane_thermostat', 'hvac_action') }}
  - name: Downstairs cooling
    state: >
      {% if is_state_attr('climate.downstairs_trane_thermostat', 'hvac_action', 'cooling') %}
        {{ 1 | int }}
      {% else %}
        {{ 0 | int }}
      {% endif %}
  - name: Pool Temp
    unit_of_measurement: '°F'
    state: >
      {{ state_attr('climate.pentair_fb_bb_80_pool_heat', 'current_temperature') }}
  - name: Center Volume
    state: >
      {{ state_attr('media_player.xantech8_center', 'volume_level') | round(2)}}
  - name: Front Volume
    state: >
      {{ state_attr('media_player.xantech8_front', 'volume_level') | round(2)}}
  - name: Rear Volume
    state: >
        {{ state_attr('media_player.xantech8_rear', 'volume_level') | round(2)}}
  - name: 1 Hr Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: "{{ ((states('sensor.1_hr_usage') | float)/1000) | round(3) }}"
  - name: 50 Min Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: "{{ (states('sensor.50_min_usage') | float)/1000 }}"
  - name: 20 Min Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: "{{ (states('sensor.medium_usage') | float)/1000 }}"
  - name: 25 Min Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: "{{ (states('sensor.usage_25') | float)/1000 }}"
  - name: 40 Min Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: "{{ (states('sensor.medium_long_usage') | float)/1000 }}"
  - name: 10 Min Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: "{{ (states('sensor.fast_usage') | float)/1000 }}"
  - name: "Peak Time Usage"
    unit_of_measurement: 'W'
    state: >
      {% if is_state("binary_sensor.is_peak_time", "on") %}
        {{ states('sensor.energy_usage') }}
      {% else %}
        {{ 0 | float }}
      {% endif %}
  - name: 1 Hr Peak Time Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: >
      {% if is_state("binary_sensor.is_peak_time", "on") %}
        {{ ((states('sensor.1_hr_peak_time_usage') | float)/1000) }}
      {% else %}
        {{ 0 | float }}
      {% endif %}
  - name: 55 Min Peak Time Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: >
      {% if is_state("binary_sensor.is_peak_time", "on") %}
        {{ ((states('sensor.55_min_peak_time_usage') | float)/1000) }}
      {% else %}
        {{ 0 | float }}
      {% endif %}
  - name: 50 Min Peak Time Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: >
      {% if is_state("binary_sensor.is_peak_time", "on") %}
        {{ ((states('sensor.50_min_peak_time_usage') | float)/1000) }}
      {% else %}
        {{ 0 | float }}
      {% endif %}
  - name: 25 Min Peak Time Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: >
      {% if is_state("binary_sensor.is_peak_time", "on") %}
        {{ ((states('sensor.25_min_peak_time_usage') | float)/1000) }}
      {% else %}
        {{ 0 | float }}
      {% endif %}
  - name: 15 Min Peak Time Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: >
      {% if is_state("binary_sensor.is_peak_time", "on") %}
        {{ ((states('sensor.15_min_peak_time_usage') | float)/1000) }}
      {% else %}
        {{ 0 | float }}
      {% endif %}
  - name: 5 Min Peak Time Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: >
      {% if is_state("binary_sensor.is_peak_time", "on") %}
        {{ ((states('sensor.5_min_peak_time_usage') | float)/1000) }}
      {% else %}
        {{ 0 | float }}
      {% endif %}
  - name: Medium Peak Time Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: >
      {% if is_state("binary_sensor.is_peak_time", "on") %}
        {{ ((states('sensor.medium_peak_time_usage') | float)/1000) }}
      {% else %}
        {{ 0 | float }}
      {% endif %}
  - name: Medium Long Peak Time Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: >
      {% if is_state("binary_sensor.is_peak_time", "on") %}
        {{ ((states('sensor.medium_long_peak_time_usage') | float)/1000) }}
      {% else %}
        {{ 0 | float }}
      {% endif %}
  - name: Fast Peak Time Demand
    unit_of_measurement: 'kWh'
    icon: "mdi:flash"
    state: >
      {% if is_state("binary_sensor.is_peak_time", "on") %}
        {{ ((states('sensor.fast_peak_time_usage') | float)/1000) }}
      {% else %}
        {{ 0 | float }}
      {% endif %}

- binary_sensor:
  - name: is_peak_time
    default_entity_id: binary_sensor.is_peak_time
    state: >
      {# all days set below to test on a sunday #}
      {% if now().weekday() in (0,1,2,3,4) and now().hour >= 16 and now().hour < 19 %}
        on
      {% else %}
        off
      {% endif %}
- light:
  - name: family_room_log_light
    default_entity_id: light.family_room_log_light
    turn_on: []
    turn_off: []
    set_level: []
  - name: breakfast_area_log_light
    default_entity_id: light.breakfast_area_log_light
    turn_on: []
    turn_off: []
    set_level: []
  - name: kitchen_log_light
    default_entity_id: light.kitchen_log_light
    turn_on: []
    turn_off: []
    set_level: []

#template:
#  - number:
#    - name: Family room TV volume
#      state: "{{ (states('input_number.family_room_tv_volume') | float) | round(2) }}"

influxdb:
  api_version: 1
  host: 192.168.0.123 # js3
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  tags_attributes:
    - friendly_name
  include:
    domains:
      - sensor
      - input_number
      - media_player
      - select

utility_meter:
  daily_energy:
    source: sensor.energy_usage
    name: Daily Energy Meter
    # cycle: daily
    # Hack: cycle 1 min before midnight to 
    # keep the timestamp on the current day
    cron: "59 23 * * *"
    tariffs:
      - peak
      - offpeak
  monthly_energy:
    source: sensor.energy_usage
    name: Monthly Energy Meter
    cycle: monthly
    offset:
      days: 5
    tariffs:
      - peak
      - offpeak
