# Pentair switches
- platform: mqtt
  name:  pentair_water_feature
  command_topic: pentair/circuit/500/command
  state_topic: pentair/circuit/500/state

- platform: mqtt
  name: pentair_pool_light
  command_topic: pentair/circuit/501/command
  state_topic: pentair/circuit/501/state

- platform: mqtt
  name: pentair_floor_cleaner
  command_topic: pentair/circuit/502/command
  state_topic: pentair/circuit/502/state

- platform: mqtt
  name: pentair_high_speed
  command_topic: pentair/circuit/503/command
  state_topic: pentair/circuit/503/state

- platform: mqtt
  name: pentair_pool
  command_topic: pentair/circuit/505/command
  state_topic: pentair/circuit/505/state

- platform: template
  switches:
    aerate_the_pool:
      friendly_name: Pool Aeration
      icon_template: mdi:chart-bubble
      # value_template: "{{ is_state_attr('switch.pentair_floor_cleaner', 'sensor_state', 'on') and is_state_attr('switch.pentair_water_feature', 'sensor_state', 'on') and is_state_attr('switch.pentair_high_speed', 'sensor_state', 'on') }}"
      turn_on:
        service: homeassistant.turn_on
        data: 
          entity_id: group.pool_aeration
      turn_off:
        service: homeassistant.turn_off
        data:
          entity_id: group.pool_aeration
