resources:
  - url: /local/dual-thermostat/dual-thermostat.js?v=1
    type: js
title: The Jones House
views:
  - badges: []
    cards:
      - entities:
          - switch.zooz_zen21_switch_v2_0_switch
        show_header_toggle: true
        title: Front Yard Lights
        type: entities
      - entities:
          - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
          - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_2
          - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_3
          - switch.zooz_zen21_switch_v2_0_switch_2
          - switch.zooz_zen21_switch_v2_0_switch_3
        show_header_toggle: true
        title: All Inside Lights
        type: entities
      - entities:
          - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_4
        show_header_toggle: true
        title: Back Yard Lights
        type: entities
    path: default_view
    title: Lights
  - badges: []
    cards:
      - entities:
          - entity: climate.trane_corporation_model_tzemt524aa21ma_cooling_1
            type: cool
          - entity: climate.trane_corporation_model_tzemt524aa21ma_heating_1
            type: heat
        name: Downstairs
        type: 'custom:dual-thermostat'
      - entities:
          - entity: climate.trane_corporation_model_tzemt524aa21ma_cooling_1_2
            type: cool
          - entity: climate.trane_corporation_model_tzemt524aa21ma_heating_1_2
            type: heat
        name: Upstairs
        type: 'custom:dual-thermostat'
      - entities:
          - sensor.ambient_temp_1
          - sensor.ambient_temp_2
          - sensor.ambient_temp_3
          - sensor.ambient_temp_5
          - sensor.ambient_temp_6
          - sensor.ambient_temp_7
          - sensor.ambient_temp_8
        hours_to_show: 24
        refresh_interval: 60
        title: Indoor Temps
        type: history-graph
      - entities:
          - sensor.ambient_temp_1
          - sensor.ambient_temp_2
          - sensor.ambient_temp_3
          - sensor.ambient_temp_4
          - sensor.ambient_temp_5
          - sensor.ambient_temp_6
          - sensor.ambient_temp_7
          - sensor.ambient_temp_8
          - sensor.ambient_temp
        show_header_toggle: false
        title: All Temperatures
        type: entities
      - entities:
          - sun.sun
          - sensor.ambient_temp_1
          - sensor.ambient_uv
          - sensor.ambient_temp
          - sensor.ambient_humidity
          - sensor.ambient_wind_speed
          - sensor.ambient_wind_gust
        show_header_toggle: false
        title: Current Weather
        type: entities
    path: climate
    title: Climate
  - badges: []
    cards:
      - entities:
          - sensor.energy_usage
          - sensor.fast_demand
          - sensor.medium_demand
          - sensor.medium_long_demand
          - sensor.1_hr_demand
        show_header_toggle: false
        title: Home Energy Usage
        type: entities
      - entities:
          - sensor.fast_demand
          - sensor.medium_demand
          - sensor.medium_long_demand
          - sensor.1_hr_demand
        hours_to_show: 24
        refresh_interval: 60
        title: Detailed Demand
        type: history-graph
    path: energy
    title: energy
  - badges: []
    cards:
      - entities:
          - sensor.ambient_temp_1
          - sensor.upstairs_setpoint
          - sensor.upstairs_state
        hours_to_show: 24
        refresh_interval: 60
        title: Upstairs
        type: history-graph
      - entities:
          - sensor.ambient_temp_2
          - sensor.downstairs_setpoint
          - sensor.downstairs_state
        hours_to_show: 24
        refresh_interval: 60
        title: Downstairs
        type: history-graph
      - entities:
          - sensor.1_hr_demand
          - sensor.ambient_temp
        hours_to_show: 24
        refresh_interval: 60
        title: Demand
        type: history-graph
    path: load_status
    title: Load Status
  - badges: []
    cards:
      - entities:
          - input_number.kwh_limit
          - input_number.hi_temp
          - input_number.target_temp
          - input_number.precool_temp
          - input_number.upstairs_setpoint
          - input_number.downstairs_setpoint
        show_header_toggle: false
        title: Climate/Energy Control
        type: entities
    path: energy_control
    title: Energy control
