#resources:
#  - url: /local/dual-thermostat/dual-thermostat.js?v=1
#    type: js
title: The Jones House
views:
  - badges: []
    #
    # lighting control
    #
    title: Control
    path: default_view
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Outside Lights
            cards:
              - type: entity-button
                entity: light.front_outside # switch.front_lights
#              - type: entity-button
#                entity: switch.christmas_lights
              - type: entity-button
                entity: light.back_patio # switch.back_patio_lights
              - type: entity-button
                entity: light.back_string # switch.string_lights
              - type: entity-button
                entity: light.pentair_fb_bb_80_pool_light
          - type: horizontal-stack
            title: Inside Lights
            cards:
              - type: entity-button
                entity: light.family_room_floor_lamp # switch.family_room_light
              - type: entity-button
                entity: switch.family_room_ceiling_fan
              - type: entity-button
                entity: switch.family_room_ceiling_light
              - type: entity-button
                entity: light.family_room
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: light.breakfast_area
              - type: entity-button
                entity: light.kitchen # switch.kitchen_lights
              - type: entity-button
                entity: light.under_cabinets
              - type: entity-button
                entity: light.front_room_lamp # switch.front_room_light
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: light.master_floor_lamp # switch.master_light
              - type: entity-button
                entity: light.loft_floor_lamp # switch.loft_light
              - type: entity-button
                entity: light.desk # switch.desk_lights
              - type: entity-button
                entity: light.stairs # switch.stair_lights
      #
      # Patio screens
      #
      - type: vertical-stack
        title: Patio Screens
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: cover.back_patio_screens
                state_color: false
              - type: entity-button
                entity: cover.west_patio_screen
                state_color: false
              - type: entity-button
                entity: cover.middle_patio_screen
                state_color: false
              - type: entity-button
                entity: cover.east_patio_screen
                state_color: false
      #
      # Garage doors
      #
      - type: vertical-stack
        title: Garage Doors
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: cover.large_garage_door_controller
                icon: mdi:garage-variant
              - type: entity-button
                entity: cover.small_garage_door_controller
                icon: mdi:garage
      #
      # Thermostats
      #
      - type: vertical-stack
        title: Thermostats
        cards:
        - name: Upstairs
          type: thermostat
          entity: climate.upstairs_trane_thermostat
        - name: Downstairs
          type: thermostat
          entity: climate.downstairs_trane_thermostat
        - name: false
          type: custom:numberbox-card
          entity: input_number.target_temp
          # name: false
          card_mod:
            style: |
              .cur-box ha-icon{ transform:scale(2); }
              .body .cur-num { font-size:30px }
              .body{display:block!important}
              .body::after{text-align:center;font-size:20px;content:"Target Temperature";display:block!important}

#
      # Pool filter
      #
      - type: vertical-stack
        title: Pool
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: switch.pentair_fb_bb_80_pool
              - type: entity-button
                entity: switch.pentair_fb_bb_80_water_feature
              - type: entity-button
                entity: switch.pentair_fb_bb_80_floor_cleaner
              - type: entity-button
                # entity: switch.pentair_high_speed
                entity: switch.pentair_fb_bb_80_high_speed
      #
      # Pool Lights
      #
      - type: vertical-stack
        title: Pool Light Colors
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: script.pentair_lights_red
                name: Red
                icon: mdi:radiobox-marked
                tap_action:
                  action: call-service
                  service: script.pentair_lights_red
              - type: entity-button
                entity: script.pentair_lights_purple
                name: Purple
                icon: mdi:radiobox-marked
                tap_action:
                  action: call-service
                  service: script.pentair_lights_purple
              - type: entity-button
                entity: script.pentair_lights_green
                name: Green
                icon: mdi:radiobox-marked
                tap_action:
                  action: call-service
                  service: script.pentair_lights_green
              - type: entity-button
                entity: script.pentair_lights_white
                name: White
                icon: mdi:radiobox-marked
                tap_action:
                  action: call-service
                  service: script.pentair_lights_white
              - type:  entity-button
                entity: script.pentair_lights_blue
                name: Blue
                icon: mdi:radiobox-marked
                tap_action:
                  action: call-service
                  service: script.pentair_lights_blue
          - type: horizontal-stack
            title: Pool Light Modes
            cards:
              - type: entity-button
                entity: script.pentair_lights_party
                name: Party
                icon: mdi:party-popper
                tap_action:
                  action: call-service
                  service: script.pentair_lights_party
              - type: entity-button
                entity: script.pentair_lights_american
                name: American
                icon: mdi:flag
                tap_action:
                  action: call-service
                  service: script.pentair_lights_american
              - type: entity-button
                entity: script.pentair_lights_romance
                name: Romance
                icon: mdi:heart
                tap_action:
                  action: call-service
                  service: script.pentair_lights_romance
              - type: entity-button
                entity: script.pentair_lights_california_sunset
                name: California Sunset
                icon: mdi:weather-sunset
                tap_action:
                  action: call-service
                  service: script.pentair_lights_california_sunset
              - type: entity-button
                entity: script.pentair_lights_caribbean
                name: Caribbean
                icon: mdi:palm-tree
                tap_action:
                  action: call-service
                  service: script.pentair_lights_caribbean
              - type: entity-button
                entity: script.pentair_lights_royal
                name: Royal
                icon: mdi:crown
                tap_action:
                  action: call-service
                  service: script.pentair_lights_royal

      - type: vertical-stack
        title: Wind Settings
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - input_number.wind_threshold
      - type: vertical-stack
        title: Hot Tub Settings
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - climate.hot_tub
              - input_number.hot_tub_run_temp
              - input_number.hot_tub_rest_temp
  - badges: []
    #
    # Temps
    #
    title: Data
    path: data
    cards:
      #
      # indoor temperature values
      #
      - type: vertical-stack
        title: Temperatures
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.ambient_temp_1
                name: Upstairs
              - type: sensor
                entity: sensor.ambient_temp_2
                name: Downstairs
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.ambient_temp_3
                name: Hair
              - type: sensor
                entity: sensor.ambient_temp_4
                name: Garage
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.ambient_temp_5
              - type: sensor
                entity: sensor.ambient_temp_6
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.ambient_temp_7
              - type: sensor
                entity: sensor.ambient_temp_8
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.ambient_temp
              - type: sensor
                entity: sensor.pool_temp

      #
      # indoor temperature graphs
      #
      - type: vertical-stack
        title: Temperatures
        cards:
          - type: history-graph
            hours_to_show: 24
            refresh_interval: 60
            entities:
              - sensor.ambient_temp_1
              - sensor.ambient_temp_2
              - sensor.ambient_temp_3
              - sensor.ambient_temp_5
              - sensor.ambient_temp_6
              - sensor.ambient_temp_7
              - sensor.ambient_temp_8
      #
      # weather
      #
      - title: Current Weather
        type: entities
        show_header_toggle: false
        entities:
          - sensor.ambient_uv
          - sensor.ambient_humidity
          - sensor.ambient_wind_speed
          - sensor.ambient_wind_gust
      - title: Backyard Wind
        type: history-graph
        hours_to_show: 1
        refresh_interval: 10
        entities:
          - sensor.ambient_wind_speed
          - sensor.ambient_wind_gust
          - sensor.peak_wind_gust
  - badges: []
    #
    # load status
    #
    title: Load
    path: load
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.energy_usage
          - type: sensor
            entity: sensor.1_hr_demand
      
      #
      # upstairs climate graph
      #
      - title: Upstairs
        type: history-graph
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - sensor.ambient_temp_1
          - sensor.upstairs_cool_setpoint
          - sensor.upstairs_heat_setpoint
          - sensor.upstairs_state
      #
      # downstairs climate graph
      #
      - hours_to_show: 24
        refresh_interval: 60
        title: Downstairs
        type: history-graph
        entities:
          - sensor.ambient_temp_2
          - sensor.downstairs_cool_setpoint
          - sensor.downstairs_heat_setpoint
          - sensor.downstairs_state
      #
      # hot tub climate graph
      #
      - title: Hot tub
        type: history-graph
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - climate.hot_tub

      #
      # demand/temperature graph
      #
      - title: Demand
        type: history-graph
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - sensor.1_hr_demand
          - sensor.1_hr_peak_time_demand
          - sensor.energy_usage
          - sensor.ambient_temp
          - sensor.upstairs_cooling
          - sensor.downstairs_cooling
    #
    # audio control
    #
  - badges: []
    title: A/V
    path: audio
    cards:
      - type: custom:mini-media-player
        entity: media_player.xantech8_front
        max_volume: 100
        group: true
        hide:
          controls: true
      - type: custom:mini-media-player
        entity: media_player.xantech8_center
        max_volume: 100
        group: true
        hide:
          controls: true
      - type: custom:mini-media-player
        entity: media_player.xantech8_rear
        max_volume: 100
        group: true
        hide:
          controls: true
      - type: custom:mini-media-player
        entity: media_player.xantech8_patio
        max_volume: 100
        group: true
        hide:
          controls: true
      - type: custom:mini-media-player
        # Family room
        entity: media_player.fire_tv_192_168_0_11
        artwork: cover
      - type: custom:mini-media-player
        # Loft
        entity: media_player.fire_tv_192_168_0_15
        artwork: cover
      - type: custom:mini-media-player
        # Patio
        entity: media_player.fire_tv_192_168_0_60
        artwork: cover
      - type: horizontal-stack
        title: Audio
        cards:
          - type: button
            entity: scene.tv_audio
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.tv_audio
          - type: button
            entity: scene.party_audio_on
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.party_audio_on
          - type: button
            entity: scene.patio_tv_audio_on
            tap_action:
              action: call-service
              service: scene.turn_on
              service_data:
                entity_id: scene.patio_tv_audio_on
      - type: button
        entity: scene.tv_audio_off
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data:
            entity_id: scene.tv_audio_off

  - badges: []
    title: EM
    path: energy
    visible:
      user: eric
    cards:
      #
      # slider controls
      #
      - type: vertical-stack
        title: Climate/Energy Control
        cards:
          - type: entities
            show_header_toggle: false
            entities:
              - input_boolean.summer_energy_mode
              - input_boolean.summer_screen_mode
              #- input_number.kwh_limit
              #- input_number.demand_warning_level
              #- input_number.precool_temp
              #- input_number.hi_temp
              #- input_number.wake_temp
              #- input_number.target_temp
              #- input_number.sleep_temp
    #              - input_number.daytime_heat
    #              - input_number.nighttime_heat
          - type: horizontal-stack
            cards:
            - type: custom:numberbox-card
              entity: input_number.precool_temp
              name: false
              icon: false
              card_mod:
                  style: |
                    .body{display:block!important}
                    .body::after{text-align:center;font-size:10px;content:"Precool";display:block!important}
            - type: custom:numberbox-card
              entity: input_number.hi_temp
              name: false
              icon: false
              card_mod:
                  style: |
                    .body{display:block!important}
                    .body::after{text-align:center;font-size:10px;content:"High Limit";display:block!important}
          - type: horizontal-stack
            cards:
            - type: custom:numberbox-card
              name: false
              entity: input_number.sleep_temp
              card_mod:
                  style: |
                    .body{display:block!important}
                    .body::after{text-align:center;font-size:10px;content:"Wake";display:block!important}
            - type: custom:numberbox-card
              name: false
              entity: input_number.wake_temp
              card_mod:
                  style: |
                    .body{display:block!important}
                    .body::after{text-align:center;font-size:10px;content:"Sleep";display:block!important}
          - type: horizontal-stack
            cards:
            - type: custom:numberbox-card
              entity: input_number.kwh_limit
              name: false
              icon: false
              card_mod:
                  style: |
                    .body{display:block!important}
                    .body::after{text-align:center;font-size:10px;content:"Demand Limit";display:block!important}
            - type: custom:numberbox-card
              entity: input_number.demand_warning_level
              name: false
              icon: false
              card_mod:
                  style: |
                    .body{display:block!important}
                    .body::after{text-align:center;font-size:10px;content:"Warn Level";display:block!important}
