#resources:
#  - url: /local/dual-thermostat/dual-thermostat.js?v=1
#    type: js
title: The Jones House
views:
  - badges: []
    #
    # lighting control
    #
    title: Lights
    path: default_view
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Outside
            cards:
              - type: entity-button
                entity: switch.front_lights
              - type: entity-button
                entity: switch.christmas_lights
              - type: entity-button
                entity: switch.string_lights
          - type: horizontal-stack
            title: Inside
            cards:
              - type: entity-button
                entity: switch.dining_room_light
              - type: entity-button
                entity: switch.family_room_light
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: switch.loft_light
              - type: entity-button
                entity: switch.desk_lights
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: switch.stair_lights
              - type: entity-button
                entity: switch.breakfast_area_light
                name: Breakfast Area
  - badges: []
    #
    # thermostat controls & temps
    #
    title: Air
    path: air
    cards:
      - type: vertical-stack
        cards:
          #
          # upstairs thermostat control
          #
          - name: Upstairs
            type: 'thermostat'
            entity: climate.trane_corporation_model_tzemt524aa21ma_mode_2
          - title: Upstairs state
            type: history-graph
            hours_to_show: 24
            refresh_interval: 60
            entities:
              - sensor.upstairs_state
          #
          # downstairs thermostat control
          #
          - name: Downstairs
            type: 'thermostat'
            entity: climate.trane_corporation_model_tzemt524aa21ma_mode
          - title: Downstairs state
            type: history-graph
            hours_to_show: 24
            refresh_interval: 60
            entities:
              - sensor.downstairs_state
  - badges: []
    #
    # thermostat controls & temps
    #
    title: Temps
    path: temps
    cards:
      #
      # indoor temperature values
      #
      - type: vertical-stack
        title: Temperatures
        cards:
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.ambient_temp_1
                name: Upstairs
              - type: sensor
                entity: sensor.ambient_temp_2
                name: Downstairs
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.ambient_temp_3
                name: Hair
              - type: sensor
                entity: sensor.ambient_temp_4
                name: Garage
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.ambient_temp_5
              - type: sensor
                entity: sensor.ambient_temp_6
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.ambient_temp_7
              - type: sensor
                entity: sensor.ambient_temp_8
          - type: sensor
            entity: sensor.ambient_temp
      #
      # indoor temperature graphs
      #
      - title: Indoor Temps
        type: history-graph
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - sensor.ambient_temp_1
          - sensor.ambient_temp_2
          - sensor.ambient_temp_3
          - sensor.ambient_temp_5
          - sensor.ambient_temp_6
          - sensor.ambient_temp_7
          - sensor.ambient_temp_8
      #
      # weather
      #
      - title: Current Weather
        type: entities
        show_header_toggle: false
        entities:
          - sensor.ambient_uv
          - sensor.ambient_humidity
          - sensor.ambient_wind_speed
          - sensor.ambient_wind_gust
  - badges: []
    #
    # pool control
    #
    title: Pool
    path: pool
    cards:
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          title: Controls
          cards:
            - type: entity-button
              icon: mdi:waves
              entity: switch.pentair_water_feature
            - type: entity-button
              icon: mdi:lightbulb
              entity: switch.pentair_pool_light
        - type: horizontal-stack
          cards:
            - type: entity-button
              icon: mdi:pump
              entity: switch.pentair_floor_cleaner
            - type: entity-button
              icon: mdi:pump
              entity: switch.pentair_high_speed
        - type: sensor
          entity: sensor.pentair_pooltemp
        - type: horizontal-stack
          title: Light Colors
          cards:
            - type: vertical-stack
              cards:
                - type: entity-button
                  entity: script.pentair_lights_red
                  name: Red
                  icon: mdi:radiobox-marked
                  tap_action:
                    action: call-service
                    service: script.pentair_lights_red
                - type: entity-button
                  entity: script.pentair_lights_purple
                  name: Purple
                  icon: mdi:radiobox-marked
                  tap_action:
                    action: call-service
                    service: script.pentair_lights_purple
            - type: vertical-stack
              cards:
                - type: entity-button
                  entity: script.pentair_lights_green
                  name: Green
                  icon: mdi:radiobox-marked
                  tap_action:
                    action: call-service
                    service: script.pentair_lights_green
                - type: entity-button
                  entity: script.pentair_lights_white
                  name: White
                  icon: mdi:radiobox-marked
                  tap_action:
                    action: call-service
                    service: script.pentair_lights_white
            - type: vertical-stack
              cards:
                - type:  entity-button
                  entity: script.pentair_lights_blue
                  name: Blue
                  icon: mdi:radiobox-marked
                  tap_action:
                    action: call-service
                    service: script.pentair_lights_blue
        - type: horizontal-stack
          title: Light Modes
          cards:
            - type: vertical-stack
              cards:
                - type: entity-button
                  entity: script.pentair_lights_party
                  name: Party
                  icon: mdi:party-popper
                  tap_action:
                    action: call-service
                    service: script.pentair_lights_party
                - type: entity-button
                  entity: script.pentair_lights_american
                  name: American
                  icon: mdi:flag
                  tap_action:
                    action: call-service
                    service: script.pentair_lights_american
            - type: vertical-stack
              cards:
                - type: entity-button
                  entity: script.pentair_lights_romance
                  name: Romance
                  icon: mdi:heart
                  tap_action:
                    action: call-service
                    service: script.pentair_lights_romance
                - type: entity-button
                  entity: script.pentair_lights_california_sunset
                  name: California Sunset
                  icon: mdi:weather-sunset
                  tap_action:
                    action: call-service
                    service: script.pentair_lights_california_sunset
            - type: vertical-stack
              cards:
                - type: entity-button
                  entity: script.pentair_lights_caribbean
                  name: Caribbean
                  icon: mdi:palm-tree
                  tap_action:
                    action: call-service
                    service: script.pentair_lights_caribbean
                - type: entity-button
                  entity: script.pentair_lights_royal
                  name: Royal
                  icon: mdi:crown
                  tap_action:
                    action: call-service
                    service: script.pentair_lights_royal
  #    cards:
  #    - type: vertical-stack
  #      title: Pool
  #      cards:
  #        - type: horizontal-stack
  #          cards:
  #            - type: entity-button
  #              icon: mdi:pump
  #              entity: switch.pentair_water_feature
  #            - type: entity-button
  #              icon: mdi:lightbulb
  #              entity: switch.pentair_pool_light
  #        - type: horizontal-stack
  #          cards:
  #            - type: entity-button
  #              icon: mdi:pump
  #              entity: switch.pentair_floor_cleaner
  #            - type: entity-button
  #              icon: mdi:pump
  #              entity: switch.pentair_high_speed

  - badges: []
    #
    # load status
    #
    title: Load
    path: load
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.energy_usage
          - type: sensor
            entity: sensor.1_hr_demand
      #
      # upstairs climate graph
      #
      - title: Upstairs
        type: history-graph
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - sensor.ambient_temp_1
          - sensor.upstairs_cool_setpoint
          - sensor.upstairs_heat_setpoint
          - sensor.upstairs_state
      #
      # downstairs climate graph
      #
      - hours_to_show: 24
        refresh_interval: 60
        title: Downstairs
        type: history-graph
        entities:
          - sensor.ambient_temp_2
          - sensor.downstairs_cool_setpoint
          - sensor.downstairs_heat_setpoint
          - sensor.downstairs_state
      #
      # demand/temperature graph
      #
      - title: Demand
        type: history-graph
        hours_to_show: 24
        refresh_interval: 60
        entities:
          - sensor.1_hr_demand
          - sensor.ambient_temp
  - badges: []
    #
    # energy control
    #
    title: Energy control
    path: energy_control
    cards:
      #
      # slider controls
      #
      - title: Climate/Energy Control
        type: entities
        show_header_toggle: false
        entities:
          - input_number.kwh_limit
          - input_number.hi_temp
          - input_number.target_temp
          - input_number.precool_temp
          - input_number.daytime_heat
          - input_number.nighttime_heat
#  - badges: []
#    #
#    # energy usage
#    #
#    title: Energy
#    path: energy
#    cards:
#      #
#      # demand values
#      #
#      - title: Home Energy Usage
#        type: sensor
#        show_header_toggle: false
#        entities:
#          - sensor.energy_usage
#          - sensor.fast_demand
#          - sensor.medium_demand
#          - sensor.medium_long_demand
#          - sensor.1_hr_demand
#      #
#      # demand graphs
#      #
#      - title: Detailed Demand
#        type: history-graph
#        hours_to_show: 24
#        refresh_interval: 60
#        entities:
#          - sensor.fast_demand
#          - sensor.medium_demand
#          - sensor.medium_long_demand
#          - sensor.1_hr_demand
