# Ambient weather station and temperatures
# see https://www.home-assistant.io/components/ambient_station/

- platform: ambient_station
  api_key: !secret ambient_api_key
  app_key: !secret ambient_app_key
  monitored_conditions:
    - temp1f
    - temp2f
    - temp3f
    - temp4f
    - temp5f
    - temp6f
    - temp7f
    - temp8f    
    - tempf
    - humidity
    - windspdmph_avg2m
    - battout
    - batt1
    - batt2
    - batt3
    - batt4
    - batt5
    - batt6
    - batt7
    - batt8
