- platform: template
  sensors:
    #
    # Upstairs
    #
    pool_temperature:
      friendly_name: Pool Temp
      unit_of_measurement: '°F'
      value_template: >
        {{ state_attr('climate.pentair_fb_bb_80_pool_heat', 'current_temperature') }}
