# Climate sensors from Trane
- platform: template
  sensors:
    #
    # Downstairs
    #
    upstairs_trane_temperature:
      friendly_name: Upstairs Trane Temperature
      unit_of_measurement: '°F'
      value_template: "{{ state_attr('climate.upstairs_trane_thermostat', 'current_temperature') }}"
    upstairs_cool_setpoint:
      friendly_name: Upstairs Cool Setpoint
      unit_of_measurement: '°F'
      value_template: "{{ state_attr('climate.upstairs_trane_thermostat', 'target_temp_high') }}"
    upstairs_heat_setpoint:
      friendly_name: Upstairs Heat Setpoint
      unit_of_measurement: '°F'
      value_template: "{{ state_attr('climate.upstairs_trane_thermostat', 'target_temp_low') }}"
    upstairs_state:
      friendly_name: Upstairs State
      value_template: "{{ state_attr('climate.upstairs_trane_thermostat', 'hvac_action') }}"
    upstairs_cooling:
      friendly_name: Upstairs is cooling
      value_template: >
        {% if is_state_attr('climate.upstairs_trane_thermostat', 'hvac_action', 'cooling') %}
          {{ 1 | int }}
        {% else %}
          {{ 0 | int }}
        {% endif %}

    #
    # Downstairs
    #
    downstairs_trane_temperature:
      friendly_name: Downstairs Trane Temperature
      unit_of_measurement: '°F'
      value_template: "{{ state_attr('climate.downstairs_trane_thermostat', 'current_temperature') }}"
    downstairs_cool_setpoint:
      friendly_name: Downstairs Cool Setpoint
      unit_of_measurement: '°F'
      value_template: "{{ state_attr('climate.downstairs_trane_thermostat', 'target_temp_high') }}"
    downstairs_heat_setpoint:
      friendly_name: Downstairs Heat Setpoint
      unit_of_measurement: '°F'
      value_template: "{{ state_attr('climate.downstairs_trane_thermostat', 'target_temp_low') }}"
    downstairs_state:
      friendly_name: Downstairs State
      value_template: "{{ state_attr('climate.downstairs_trane_thermostat', 'hvac_action') }}"
    downstairs_cooling:
      friendly_name: Downstairs is cooling
      value_template: >
        {% if is_state_attr('climate.downstairs_trane_thermostat', 'hvac_action', 'cooling') %}
          {{ 1 | int }}
        {% else %}
          {{ 0 | int }}
        {% endif %}
