# Pentair sensors
- platform: mqtt
  name: pentair_pooltemp
  state_topic: pentair/pooltemp/state
- platform: mqtt
  name: pentair_spatemp
  state_topic: pentair/spatemp/state
- platform: mqtt
  name: pentair_airtemp
  state_topic: pentair/airtemp/state
- platform: mqtt
  name: pentair_alkalinity
  state_topic: pentair/alkalinity/state
- platform: mqtt
  name: pentair_calcium
  state_topic: pentair/calcium/state
- platform: mqtt
  name: pentair_cyanuricacid
  state_topic: pentair/cyanuricacid/state
- platform: mqtt
  name: pentair_ph
  state_topic: pentair/ph/state
- platform: mqtt
  name: pentair_orp
  state_topic: pentair/orp/state
- platform: mqtt
  name: pentair_saltppm
  state_topic: pentair/saltppm/state
- platform: mqtt
  name: pentair_saltcellstatus
  state_topic: pentair/saltcellstatus/state
- platform: mqtt
  name: pentair_saltcelllevel1
  state_topic: pentair/saltcelllevel1/state
- platform: mqtt
  name: pentair_saltcelllevel2
  state_topic: pentair/saltcelllevel2/state
- platform: mqtt
  name: pentair_saturation
  state_topic: pentair/saturation/state

- platform: mqtt
  name: pentair_pump0watts
  state_topic: pentair/pump/0/watts/state
- platform: mqtt
  name: pentair_pump0rpm
  state_topic: pentair/pump/0/rpm/state

- platform: mqtt
  name: pentair_pump0gpm
  state_topic: pentair/pump/0/gpm/state

- platform: mqtt
  name: pentair_pump1watts
  state_topic: pentair/pump/1/watts/state

- platform: mqtt
  name: pentair_pump1rpm
  state_topic: pentair/pump/1/rpm/state

- platform: mqtt
  name: pentair_pump1gpm
  state_topic: pentair/pump/1/gpm/state

- platform: mqtt
  name: pentair_pump2watts
  state_topic: pentair/pump/2/watts/state

- platform: mqtt
  name: pentair_pump2rpm
  state_topic: pentair/pump/2/rpm/state

- platform: mqtt
  name: pentair_pump2gpm
  state_topic: pentair/pump/2/gpm/state
