# Pentair sensors
- platform: mqtt
  name: pentair_pooltemp
  state_topic: pentair/pooltemp/state
- platform: mqtt
  name: pentair_airtemp
  state_topic: pentair/airtemp/state
- platform: mqtt
  name: pentair_pump0watts
  state_topic: pentair/pump/0/watts/state
- platform: mqtt
  name: pentair_pump0rpm
  state_topic: pentair/pump/0/rpm/state
- platform: mqtt
  name: pentair_pump0gpm
  state_topic: pentair/pump/0/gpm/state
- platform: mqtt
  name: pentair_pump1watts
  state_topic: pentair/pump/1/watts/state
- platform: mqtt
  name: pentair_pump1rpm
  state_topic: pentair/pump/1/rpm/state
- platform: mqtt
  name: pentair_pump1gpm
  state_topic: pentair/pump/1/gpm/state