- platform: template
  sensors:
    is_peak_time:
      value_template: >
        {# all days set below to test on a sunday #}
        {% if now().weekday() in (0,1,2,3,4) and now().hour >= 16 and now().hour < 19 %}
          on
        {% else %}
          off
        {% endif %}
